# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cac0ae060ae06845a705599c551cafbe137cd9d2e937f8838e83cf2f45b1ceb72955cef2c56efc5da3b8ae242dc79a7a1e11790916d779a94cf25b2368f5f2f

test:
  secret_key_base: 7a3cc8a5d6bd919dd7db97a1d91705d656c37e4df8fd7aa0f9605a41c54f139864f3500633085f7f5c65e8535ba2c204ba6b533d1dc6d795dd948cf0a53bf0c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c1feb25eb810e80f8beadaed4a38f52da993d27083bc846b0eb9d38ce9472438688a4ca28e9f42e2a1ad66e9ba44fdb8f86ded897fb33778936de0ce33827690
